config/routes.rb
Rails.application.routes.draw do
  resources :events

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all.order("created_at DESC")
  end

  def new
    @evevt = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "成功建立"
    	redirect_to :action => :index
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update
      flash[:notice] = "成功修改"
      edirect_to :action => :index
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "成功刪除"
    redirect_to :action => :index
  end

    private

    def find_event
  		@event = Event.find(params[:id])
  	end

  	def event_params
  		params.require(:event).permit(:topic, :article)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%=  simple_form_for Event.new do |f| %>
<br>
<%=  f.input :name %>
<br>
<%=  f.input :content %>
<br>
<%=  f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1><%= "Edit Post" %></h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>

app/views/events/index.html.erb
<div id="events">
  <% @events.each do |event| %>
    <div class="event">
      <h2 class="name">
        <%= link_to event.name, event %>
      </h2>
      <p class="date">
        Published at
        <%= time_ago_in_words(event.created_at) %>
      </p>
    </div>

  <% end %>

</div>

app/views/events/new.html.erb
<h1><%= "New Post" %><h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div id="event_article">
  <h1>
    <%= @event.name %>
  </h1>
  <p>
    <%= @event.content %>
  </p>
  <div id="articles">



  </div>
  <br/>
  <hr/>
  <br/>
  <%= link_to "Edit", edit_event_path(@event), class: "button" %>
  <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "確定刪除?" }, class: "button" %>
  <%= link_to "Home", root_path(@event), class: "button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
  <p>地震災情支援網</p>
</header>
<div id="buttons">
  <%= link_to "New Post", new_event_path %>
</div>

<div id="wrapper">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div id="wrapper">


<%= yield %>

</body>
</html>